Repository googleapis/java-iamcredentials, pull requests merged in 2020-09, with the labels that each got.

#216 chore: regenerate README
  README.md
  synth.metadata
Labels: api: iam, cla: yes, context: none

#218 chore: regenerate templates
  .github/CODEOWNERS
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#231 chore: add repo settings configuration
  .github/sync-repo-settings.yaml
Labels: api: iam, automerge, cla: yes

#235 chore: regenerate templates
  .github/readme/synth.py
  .github/workflows/auto-release.yaml
  .kokoro/continuous/readme.cfg
  .kokoro/readme.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#237 build: rename samples lint workflow to checkstyle to disambiguate branch protection with unit lint
  .github/workflows/samples.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full
