Repository googleapis/java-iamcredentials, pull requests merged in 2020-06, with the labels that each got.

#156 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#157 chore: regenerate with updated protoc
  proto-google-cloud-iamcredentials-v1/src/main/java/com/google/cloud/iam/credentials/v1/GenerateAccessTokenRequest.java
  proto-google-cloud-iamcredentials-v1/src/main/java/com/google/cloud/iam/credentials/v1/GenerateAccessTokenResponse.java
  proto-google-cloud-iamcredentials-v1/src/main/java/com/google/cloud/iam/credentials/v1/GenerateIdTokenRequest.java
  proto-google-cloud-iamcredentials-v1/src/main/java/com/google/cloud/iam/credentials/v1/GenerateIdTokenResponse.java
  proto-google-cloud-iamcredentials-v1/src/main/java/com/google/cloud/iam/credentials/v1/SignBlobRequest.java
  proto-google-cloud-iamcredentials-v1/src/main/java/com/google/cloud/iam/credentials/v1/SignBlobResponse.java
  proto-google-cloud-iamcredentials-v1/src/main/java/com/google/cloud/iam/credentials/v1/SignJwtRequest.java
  proto-google-cloud-iamcredentials-v1/src/main/java/com/google/cloud/iam/credentials/v1/SignJwtResponse.java
  synth.metadata
Labels: automerge, cla: yes, context: full

#159 chore(java_templates): add default CODEOWNERS files for samples reviews
  .github/CODEOWNERS
  synth.metadata
Labels: automerge, cla: yes, context: full

#161 chore: turn on renovate-bot master issue for java repos
  renovate.json
  synth.metadata
Labels: automerge, cla: yes, context: full

#163 build(java): skip lint on samples directory
  .kokoro/build.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#168 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#172 ci: switch to secret manager for sample/integration tests
  .kokoro/build.sh
  .kokoro/nightly/integration.cfg
  .kokoro/nightly/samples.cfg
  .kokoro/populate-secrets.sh
  .kokoro/presubmit/integration.cfg
  .kokoro/presubmit/samples.cfg
  .kokoro/trampoline.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#176 feat(deps): adopt flatten plugin and google-cloud-shared-dependencies
  .gitignore
  google-cloud-iamcredentials/pom.xml
  grpc-google-cloud-iamcredentials-v1/pom.xml
  pom.xml
  proto-google-cloud-iamcredentials-v1/pom.xml
Labels: cla: yes

#177 chore: update README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#183 fix: migrate to grpc_service_config
  README.md
  google-cloud-iamcredentials/src/main/java/com/google/cloud/iam/credentials/v1/stub/IamCredentialsStubSettings.java
  synth.metadata
Labels: automerge, cla: yes, context: partial

#189 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none
