Repository googleapis/java-iamcredentials, pull requests merged in 2021-07, with the labels that each got.

#479 chore: remove distributionManagement section
  pom.xml
Labels: api: iam, automerge, cla: yes

#481 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: iam, automerge, cla: yes

#482 chore: remove distributionManagement section
  google-cloud-iamcredentials-bom/pom.xml
Labels: api: iam, automerge, cla: yes

#485 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: iam, automerge, cla: yes

#484 chore: remove All rights reserved clause from java.header
  java.header
  synth.metadata
Labels: api: iam, automerge, cla: yes, context: full

#486 chore: add dependencyDashboardLabels to renovate.json
  renovate.json
  synth.metadata
Labels: api: iam, automerge, cla: yes, context: full

#487 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: iam, automerge, cla: yes, kokoro:force-run

#491 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: iam, automerge, cla: yes

#494 build: configure branch java7 as a release branch
  .github/release-please.yml
  .github/sync-repo-settings.yaml
Labels: api: iam, automerge, cla: yes

#495 feat: configure initial sp version
  .github/workflows/ci.yaml
Labels: api: iam, automerge, cla: yes
