Repository googleapis/java-iamcredentials, pull requests merged in 2021-05, with the labels that each got.

#427 build(java): switch to release-please for release tagging
  .github/release-please.yml
  synth.metadata
Labels: api: iam, automerge, cla: yes, context: none

#428 chore: add enumeration data type to .repo-metadata.json
  .repo-metadata.json
Labels: api: iam, automerge, cla: yes

#431 chore: adding cloud-rad java xrefs
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: iam, automerge, cla: yes, context: full

#433 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: iam, automerge, cla: yes

#438 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: iam, automerge, cla: yes

#439 build(java): remove codecov action
  .github/workflows/ci.yaml
  synth.metadata
Labels: api: iam, automerge, cla: yes, context: full

#441 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: iam, automerge, cla: yes

#442 chore: add changelog to cloud-rad
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: iam, automerge, cla: yes, context: full

#444 feat: add `gcf-owl-bot[bot]` to `ignoreAuthors`
  .github/generated-files-bot.yml
  synth.metadata
Labels: api: iam, automerge, cla: yes, context: full

#447 chore: dump maven version along with java
  .kokoro/build.sh
  synth.metadata
Labels: api: iam, automerge, cla: yes, context: full

#450 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: iam, automerge, cla: yes
