Repository googleapis/java-iamcredentials, pull requests merged in 2021-09, with the labels that each got.

#530 build(java): update renovate config to mark conformance tests as a test commit type
  synth.metadata
Labels: cla: yes, api: iam, automerge, context: full

#541 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: iam, automerge

#545 chore: remove readme autosynth config
  .github/readme/synth.metadata/synth.metadata
  .github/readme/synth.py
  .kokoro/continuous/readme.cfg
Labels: kokoro:force-run, cla: yes, api: iam, automerge

#540 chore: re-generated to pick up changes from synthtool
  synth.metadata
Labels: cla: yes, api: iam, automerge, context: partial

#546 chore: delete synth.py
  synth.py
Labels: cla: yes, api: iam

#561 chore: change branch master to main in sync-repo-settings.yaml
  .github/sync-repo-settings.yaml
Labels: cla: yes, api: iam, automerge

#552 chore: relocate owl bot post processor
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
  README.md
Labels: cla: yes, api: iam
